### ISSUE TITLE
[v5] frappe form control title missing after updates.

### ISSUE THREAD

**Issue by gangadharkadam** [gangadharkadam/church_ministry#4]
Hello All,
  I have used the div title for accessing the div for google map following is my code snipest ,
http://pastebin.com/aehcawZp

this is working on my local setup .
when i push same code on server and ran 'frappe--latest' the title from frappe control is missing. so the map div is not appended.

Please find the attachment for details

How to append the map div . Please suggest.

Regards,
Gangadhar kadam

![title not in frappe control latest](https://cloud.githubusercontent.com/assets/3529785/6122558/64d42eb8-b11b-11e4-8131-c828bbef926b.png)
![title for frappe control](https://cloud.githubusercontent.com/assets/3529785/6122565/8185c120-b11b-11e4-99a4-fb1bf6c4741d.png)

**Comment by pdvyas** [comment]
Please use `frappe.ui.form.on`
As answered here, https://discuss.frappe.io/t/v5-frappe-form-control-title-missing-after-updates/4694/2?u=pdvyas it is a very bad design.
use `frappe.ui.form.on` and use `$(cur_frm.get_field("lon")).append`

**Comment by gangadharkadam** [comment]
Hello Pratik,
its worked thanks
